package:
  name: multiuserblazeserver
  version: 0.2.1

source:
  git_url: ../

requirements:
  build:
    - python

  run:
    - blaze >= 0.7.2
    - into >= 0.2.1
    - python
    - pandas
    - datashape
    - flask
    - six
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{environ.get('PY_VER').replace('.', '')}}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

about:
  home: https://github.com/ContinuumIO/multiuserblazeserver
  license: BSD
